# GDSC AI/ML: Data Cleaning

## Importing Basic Libraries

In [1]:
import pandas as pd
import numpy as np

## Importing CSV File

In [2]:
df = pd.read_csv("50_Startups.csv")

In [3]:
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

## Data Cleaning Operations

### Duplicate Values

In [4]:
df.drop_duplicates()

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

### --> No Duplicate value found

### Missing Value

In [5]:
missing=df.isnull().sum()

In [6]:
missing

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

### --> No Missing value found

### --> We can see that numerical and string formatting is uniform and there is no trailing spaces or unwanted characters

## Encoding: One-hot encoding on 'State' column

### Importing required library

In [7]:
from sklearn.preprocessing import OneHotEncoder

### Checking unique values

In [8]:
df["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

### One-Hot Encoding

In [9]:
ohe= OneHotEncoder()

In [10]:
ohe.fit_transform(df[["State"]]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Assigning ohe array to variable s_array

In [11]:
s_array=ohe.fit_transform(df[["State"]]).toarray()

In [35]:
ohe.categories_[0]

array(['California', 'Florida', 'New York'], dtype=object)

### Assigning labels to feature_labels

In [36]:
feature_labels=ohe.categories_

In [37]:
pd.DataFrame(s_array, columns = feature_labels)

   California Florida New York
0         0.0     0.0      1.0
1         1.0     0.0      0.0
2         0.0     1.0      0.0
3         0.0     0.0      1.0
4         0.0     1.0      0.0
5         0.0     0.0      1.0
6         1.0     0.0      0.0
7         0.0     1.0      0.0
8         0.0     0.0      1.0
9         1.0     0.0      0.0
10        0.0     1.0      0.0
11        1.0     0.0      0.0
12        0.0     1.0      0.0
13        1.0     0.0      0.0
14        0.0     1.0      0.0
15        0.0     0.0      1.0
16        1.0     0.0      0.0
17        0.0     0.0      1.0
18        0.0     1.0      0.0
19        0.0     0.0      1.0
20        1.0     0.0      0.0
21        0.0     0.0      1.0
22        0.0     1.0      0.0
23        0.0     1.0      0.0
24        0.0     0.0      1.0
25        1.0     0.0      0.0
26        0.0     1.0      0.0
27        0.0     0.0      1.0
28        0.0     1.0      0.0
29        0.0     0.0      1.0
30        0.0     1.0      0.0
31        0.0     0.0      1.0
32        1.0     0.0      0.0
33        0.0     1.0      0.0
34        1.0     0.0      0.0
35        0.0     0.0      1.0
36        0.0     1.0      0.0
37        1.0     0.0      0.0
38        0.0     0.0      1.0
39        1.0     0.0      0.0
40        1.0     0.0      0.0
41        0.0     1.0      0.0
42        1.0     0.0      0.0
43        0.0     0.0      1.0
44        1.0     0.0      0.0
45        0.0     0.0      1.0
46        0.0     1.0      0.0
47        1.0     0.0      0.0
48        0.0     0.0      1.0
49        1.0     0.0      0.0

### Assigning encoded DataFrame to features

In [38]:
features = pd.DataFrame(s_array, columns = feature_labels)

### Merging both Dataframes

In [39]:
pd.concat([df, features], axis =1)

,R&D Spend,Administration,Marketing Spend,State,Profit,"(California,)","(Florida,)","(New York,)"
0,165349.20,136897.80,471784.10,New York,192261.83,0.0,0.0,1.0
1,162597.70,151377.59,443898.53,California,191792.06,1.0,0.0,0.0
2,153441.51,101145.55,407934.54,Florida,191050.39,0.0,1.0,0.0
3,144372.41,118671.85,383199.62,New York,182901.99,0.0,0.0,1.0
4,142107.34,91391.77,366168.42,Florida,166187.94,0.0,1.0,0.0
5,131876.90,99814.71,362861.36,New York,156991.12,0.0,0.0,1.0
6,134615.46,147198.87,127716.82,California,156122.51,1.0,0.0,0.0
7,130298.13,145530.06,323876.68,Florida,155752.60,0.0,1.0,0.0
8,120542.52,148718.95,311613.29,New York,152211.77,0.0,0.0,1.0
9,123334.88,108679.17,304981.62,California,149759.96,1.0,0.0,0.0
10,101913.08,110594.11,229160.95,Florida,146121.95,0.0,1.0,0.0
11,100671.96,91790.61,249744.55,California,144259.40,1.0,0.0,0.0
12,93863.75,127320.38,249839.44,Florida,141585.52,0.0,1.0,0.0
13,91992.39,135495.07,252664.93,California,134307.35,1.0,0.0,0.0
14,119943.24,156547.42,256512.92,Florida,132602.65,0.0,1.0,0.0
15,114523.61,122616.84,261776.23,New York,129917.04,0.0,0.0,1.0
16,78013.11,121597.55,264346.06,California,126992.93,1.0,0.0,0.0
17,94657.16,145077.58,282574.31,New York,125370.37,0.0,0.0,1.0
18,91749.16,114175.79,294919.57,Florida,124266.90,0.0,1.0,0.0
19,86419.70,153514.11,0.00,New York,122776.86,0.0,0.0,1.0
20,76253.86,113867.30,298664.47,California,118474.03,1.0,0.0,0.0
21,78389.47,153773.43,299737.29,New York,111313.02,0.0,0.0,1.0
22,73994.56,122782.75,303319.26,Florida,110352.25,0.0,1.0,0.0
23,67532.53,105751.03,304768.73,Florida,108733.99,0.0,1.0,0.0
24,77044.01,99281.34,140574.81,New York,108552.04,0.0,0.0,1.0
25,64664.71,139553.16,137962.62,California,107404.34,1.0,0.0,0.0
26,75328.87,144135.98,134050.07,Florida,105733.54,0.0,1.0,0.0
27,72107.60,127864.55,353183.81,New York,105008.31,0.0,0.0,1.0
28,66051.52,182645.56,118148.20,Florida,103282.38,0.0,1.0,0.0
29,65605.48,153032.06,107138.38,New York,101004.64,0.0,0.0,1.0
30,61994.48,115641.28,91131.24,Florida,99937.59,0.0,1.0,0.0
31,61136.38,152701.92,88218.23,New York,97483.56,0.0,0.0,1.0
32,63408.86,129219.61,46085.25,California,97427.84,1.0,0.0,0.0
33,55493.95,103057.49,214634.81,Florida,96778.92,0.0,1.0,0.0
34,46426.07,157693.92,210797.67,California,96712.80,1.0,0.0,0.0
35,46014.02,85047.44,205517.64,New York,96479.51,0.0,0.0,1.0
36,28663.76,127056.21,201126.82,Florida,90708.19,0.0,1.0,0.0
37,44069.95,51283.14,197029.42,California,89949.14,1.0,0.0,0.0
38,20229.59,65947.93,185265.10,New York,81229.06,0.0,0.0,1.0
39,38558.51,82982.09,174999.30,California,81005.76,1.0,0.0,0.0
40,28754.33,118546.05,172795.67,California,78239.91,1.0,0.0,0.0
41,27892.92,84710.77,164470.71,Florida,77798.83,0.0,1.0,0.0
42,23640.93,96189.63,148001.11,California,71498.49,1.0,0.0,0.0
43,15505.73,127382.30,35534.17,New York,69758.98,0.0,0.0,1.0
44,22177.74,154806.14,28334.72,California,65200.33,1.0,0.0,0.0
45,1000.23,124153.04,1903.93,New York,64926.08,0.0,0.0,1.0
46,1315.46,115816.21,297114.46,Florida,49490.75,0.0,1.0,0.0
47,0.00,135426.92,0.00,California,42559.73,1.0,0.0,0.0
48,542.05,51743.15,0.00,New York,35673.41,0.0,0.0,1.0
49,0.00,116983.80,45173.06,California,14681.40,1.0,0.0,0.0

### Assigning merged dataframe to df1

In [40]:
df1=pd.concat([df, features], axis =1)

### Removing 'State' column

In [41]:
df1.drop('State', axis=1)

,R&D Spend,Administration,Marketing Spend,Profit,"(California,)","(Florida,)","(New York,)"
0,165349.20,136897.80,471784.10,192261.83,0.0,0.0,1.0
1,162597.70,151377.59,443898.53,191792.06,1.0,0.0,0.0
2,153441.51,101145.55,407934.54,191050.39,0.0,1.0,0.0
3,144372.41,118671.85,383199.62,182901.99,0.0,0.0,1.0
4,142107.34,91391.77,366168.42,166187.94,0.0,1.0,0.0
5,131876.90,99814.71,362861.36,156991.12,0.0,0.0,1.0
6,134615.46,147198.87,127716.82,156122.51,1.0,0.0,0.0
7,130298.13,145530.06,323876.68,155752.60,0.0,1.0,0.0
8,120542.52,148718.95,311613.29,152211.77,0.0,0.0,1.0
9,123334.88,108679.17,304981.62,149759.96,1.0,0.0,0.0
10,101913.08,110594.11,229160.95,146121.95,0.0,1.0,0.0
11,100671.96,91790.61,249744.55,144259.40,1.0,0.0,0.0
12,93863.75,127320.38,249839.44,141585.52,0.0,1.0,0.0
13,91992.39,135495.07,252664.93,134307.35,1.0,0.0,0.0
14,119943.24,156547.42,256512.92,132602.65,0.0,1.0,0.0
15,114523.61,122616.84,261776.23,129917.04,0.0,0.0,1.0
16,78013.11,121597.55,264346.06,126992.93,1.0,0.0,0.0
17,94657.16,145077.58,282574.31,125370.37,0.0,0.0,1.0
18,91749.16,114175.79,294919.57,124266.90,0.0,1.0,0.0
19,86419.70,153514.11,0.00,122776.86,0.0,0.0,1.0
20,76253.86,113867.30,298664.47,118474.03,1.0,0.0,0.0
21,78389.47,153773.43,299737.29,111313.02,0.0,0.0,1.0
22,73994.56,122782.75,303319.26,110352.25,0.0,1.0,0.0
23,67532.53,105751.03,304768.73,108733.99,0.0,1.0,0.0
24,77044.01,99281.34,140574.81,108552.04,0.0,0.0,1.0
25,64664.71,139553.16,137962.62,107404.34,1.0,0.0,0.0
26,75328.87,144135.98,134050.07,105733.54,0.0,1.0,0.0
27,72107.60,127864.55,353183.81,105008.31,0.0,0.0,1.0
28,66051.52,182645.56,118148.20,103282.38,0.0,1.0,0.0
29,65605.48,153032.06,107138.38,101004.64,0.0,0.0,1.0
30,61994.48,115641.28,91131.24,99937.59,0.0,1.0,0.0
31,61136.38,152701.92,88218.23,97483.56,0.0,0.0,1.0
32,63408.86,129219.61,46085.25,97427.84,1.0,0.0,0.0
33,55493.95,103057.49,214634.81,96778.92,0.0,1.0,0.0
34,46426.07,157693.92,210797.67,96712.80,1.0,0.0,0.0
35,46014.02,85047.44,205517.64,96479.51,0.0,0.0,1.0
36,28663.76,127056.21,201126.82,90708.19,0.0,1.0,0.0
37,44069.95,51283.14,197029.42,89949.14,1.0,0.0,0.0
38,20229.59,65947.93,185265.10,81229.06,0.0,0.0,1.0
39,38558.51,82982.09,174999.30,81005.76,1.0,0.0,0.0
40,28754.33,118546.05,172795.67,78239.91,1.0,0.0,0.0
41,27892.92,84710.77,164470.71,77798.83,0.0,1.0,0.0
42,23640.93,96189.63,148001.11,71498.49,1.0,0.0,0.0
43,15505.73,127382.30,35534.17,69758.98,0.0,0.0,1.0
44,22177.74,154806.14,28334.72,65200.33,1.0,0.0,0.0
45,1000.23,124153.04,1903.93,64926.08,0.0,0.0,1.0
46,1315.46,115816.21,297114.46,49490.75,0.0,1.0,0.0
47,0.00,135426.92,0.00,42559.73,1.0,0.0,0.0
48,542.05,51743.15,0.00,35673.41,0.0,0.0,1.0
49,0.00,116983.80,45173.06,14681.40,1.0,0.0,0.0

In [42]:
df1=df1.drop('State', axis=1)

### Moving Profit column to the end

In [20]:
df1['Profit']=df1.pop('Profit')

In [21]:
df1

,R&D Spend,Administration,Marketing Spend,"(California,)","(Florida,)","(New York,)",Profit
0,165349.20,136897.80,471784.10,0.0,0.0,1.0,192261.83
1,162597.70,151377.59,443898.53,1.0,0.0,0.0,191792.06
2,153441.51,101145.55,407934.54,0.0,1.0,0.0,191050.39
3,144372.41,118671.85,383199.62,0.0,0.0,1.0,182901.99
4,142107.34,91391.77,366168.42,0.0,1.0,0.0,166187.94
5,131876.90,99814.71,362861.36,0.0,0.0,1.0,156991.12
6,134615.46,147198.87,127716.82,1.0,0.0,0.0,156122.51
7,130298.13,145530.06,323876.68,0.0,1.0,0.0,155752.60
8,120542.52,148718.95,311613.29,0.0,0.0,1.0,152211.77
9,123334.88,108679.17,304981.62,1.0,0.0,0.0,149759.96
10,101913.08,110594.11,229160.95,0.0,1.0,0.0,146121.95
11,100671.96,91790.61,249744.55,1.0,0.0,0.0,144259.40
12,93863.75,127320.38,249839.44,0.0,1.0,0.0,141585.52
13,91992.39,135495.07,252664.93,1.0,0.0,0.0,134307.35
14,119943.24,156547.42,256512.92,0.0,1.0,0.0,132602.65
15,114523.61,122616.84,261776.23,0.0,0.0,1.0,129917.04
16,78013.11,121597.55,264346.06,1.0,0.0,0.0,126992.93
17,94657.16,145077.58,282574.31,0.0,0.0,1.0,125370.37
18,91749.16,114175.79,294919.57,0.0,1.0,0.0,124266.90
19,86419.70,153514.11,0.00,0.0,0.0,1.0,122776.86
20,76253.86,113867.30,298664.47,1.0,0.0,0.0,118474.03
21,78389.47,153773.43,299737.29,0.0,0.0,1.0,111313.02
22,73994.56,122782.75,303319.26,0.0,1.0,0.0,110352.25
23,67532.53,105751.03,304768.73,0.0,1.0,0.0,108733.99
24,77044.01,99281.34,140574.81,0.0,0.0,1.0,108552.04
25,64664.71,139553.16,137962.62,1.0,0.0,0.0,107404.34
26,75328.87,144135.98,134050.07,0.0,1.0,0.0,105733.54
27,72107.60,127864.55,353183.81,0.0,0.0,1.0,105008.31
28,66051.52,182645.56,118148.20,0.0,1.0,0.0,103282.38
29,65605.48,153032.06,107138.38,0.0,0.0,1.0,101004.64
30,61994.48,115641.28,91131.24,0.0,1.0,0.0,99937.59
31,61136.38,152701.92,88218.23,0.0,0.0,1.0,97483.56
32,63408.86,129219.61,46085.25,1.0,0.0,0.0,97427.84
33,55493.95,103057.49,214634.81,0.0,1.0,0.0,96778.92
34,46426.07,157693.92,210797.67,1.0,0.0,0.0,96712.80
35,46014.02,85047.44,205517.64,0.0,0.0,1.0,96479.51
36,28663.76,127056.21,201126.82,0.0,1.0,0.0,90708.19
37,44069.95,51283.14,197029.42,1.0,0.0,0.0,89949.14
38,20229.59,65947.93,185265.10,0.0,0.0,1.0,81229.06
39,38558.51,82982.09,174999.30,1.0,0.0,0.0,81005.76
40,28754.33,118546.05,172795.67,1.0,0.0,0.0,78239.91
41,27892.92,84710.77,164470.71,0.0,1.0,0.0,77798.83
42,23640.93,96189.63,148001.11,1.0,0.0,0.0,71498.49
43,15505.73,127382.30,35534.17,0.0,0.0,1.0,69758.98
44,22177.74,154806.14,28334.72,1.0,0.0,0.0,65200.33
45,1000.23,124153.04,1903.93,0.0,0.0,1.0,64926.08
46,1315.46,115816.21,297114.46,0.0,1.0,0.0,49490.75
47,0.00,135426.92,0.00,1.0,0.0,0.0,42559.73
48,542.05,51743.15,0.00,0.0,0.0,1.0,35673.41
49,0.00,116983.80,45173.06,1.0,0.0,0.0,14681.40

### Exporting to preprocessed data to csv

In [22]:
df1.to_csv("50_Startups_Preprocessed.csv", index=False)

### Splitting the dataframe into features and target

In [23]:
X=df1.iloc[:, :-1]

In [24]:
Y=df1.iloc[:, -1].to_frame()

In [25]:
X

,R&D Spend,Administration,Marketing Spend,"(California,)","(Florida,)","(New York,)"
0,165349.20,136897.80,471784.10,0.0,0.0,1.0
1,162597.70,151377.59,443898.53,1.0,0.0,0.0
2,153441.51,101145.55,407934.54,0.0,1.0,0.0
3,144372.41,118671.85,383199.62,0.0,0.0,1.0
4,142107.34,91391.77,366168.42,0.0,1.0,0.0
5,131876.90,99814.71,362861.36,0.0,0.0,1.0
6,134615.46,147198.87,127716.82,1.0,0.0,0.0
7,130298.13,145530.06,323876.68,0.0,1.0,0.0
8,120542.52,148718.95,311613.29,0.0,0.0,1.0
9,123334.88,108679.17,304981.62,1.0,0.0,0.0
10,101913.08,110594.11,229160.95,0.0,1.0,0.0
11,100671.96,91790.61,249744.55,1.0,0.0,0.0
12,93863.75,127320.38,249839.44,0.0,1.0,0.0
13,91992.39,135495.07,252664.93,1.0,0.0,0.0
14,119943.24,156547.42,256512.92,0.0,1.0,0.0
15,114523.61,122616.84,261776.23,0.0,0.0,1.0
16,78013.11,121597.55,264346.06,1.0,0.0,0.0
17,94657.16,145077.58,282574.31,0.0,0.0,1.0
18,91749.16,114175.79,294919.57,0.0,1.0,0.0
19,86419.70,153514.11,0.00,0.0,0.0,1.0
20,76253.86,113867.30,298664.47,1.0,0.0,0.0
21,78389.47,153773.43,299737.29,0.0,0.0,1.0
22,73994.56,122782.75,303319.26,0.0,1.0,0.0
23,67532.53,105751.03,304768.73,0.0,1.0,0.0
24,77044.01,99281.34,140574.81,0.0,0.0,1.0
25,64664.71,139553.16,137962.62,1.0,0.0,0.0
26,75328.87,144135.98,134050.07,0.0,1.0,0.0
27,72107.60,127864.55,353183.81,0.0,0.0,1.0
28,66051.52,182645.56,118148.20,0.0,1.0,0.0
29,65605.48,153032.06,107138.38,0.0,0.0,1.0
30,61994.48,115641.28,91131.24,0.0,1.0,0.0
31,61136.38,152701.92,88218.23,0.0,0.0,1.0
32,63408.86,129219.61,46085.25,1.0,0.0,0.0
33,55493.95,103057.49,214634.81,0.0,1.0,0.0
34,46426.07,157693.92,210797.67,1.0,0.0,0.0
35,46014.02,85047.44,205517.64,0.0,0.0,1.0
36,28663.76,127056.21,201126.82,0.0,1.0,0.0
37,44069.95,51283.14,197029.42,1.0,0.0,0.0
38,20229.59,65947.93,185265.10,0.0,0.0,1.0
39,38558.51,82982.09,174999.30,1.0,0.0,0.0
40,28754.33,118546.05,172795.67,1.0,0.0,0.0
41,27892.92,84710.77,164470.71,0.0,1.0,0.0
42,23640.93,96189.63,148001.11,1.0,0.0,0.0
43,15505.73,127382.30,35534.17,0.0,0.0,1.0
44,22177.74,154806.14,28334.72,1.0,0.0,0.0
45,1000.23,124153.04,1903.93,0.0,0.0,1.0
46,1315.46,115816.21,297114.46,0.0,1.0,0.0
47,0.00,135426.92,0.00,1.0,0.0,0.0
48,542.05,51743.15,0.00,0.0,0.0,1.0
49,0.00,116983.80,45173.06,1.0,0.0,0.0

In [26]:
Y

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40